version: '3.7'

services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8084:80"
    volumes:
      - ./RESTapi:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - cmvppm-network
    depends_on:
      - php82

  php82:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./RESTapi:/var/www/html
    networks:
      - cmvppm-network

  db:
    image: mariadb:10.5.2
    restart: always
    volumes:
      - cmvppm-db-volume:/var/lib/mysql
    environment:
      TZ: "Africa/Johannesburg"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - cmvppm-network
    ports:
      - 3311:3306

volumes:
  cmvppm-db-volume:

networks:
  cmvppm-network:
    driver: bridge
